services:
  _instanceof:
    ProduitsDeFrance\ElasticsearchClientBundle\Service\ClientInterface:
      tags: 
        - !php/const ProduitsDeFrance\ElasticsearchClientBundle\Service\ClientInterface::TAG
